---
- name: Install Vector
  hosts: all
  tasks:
      - name: Upload tar.gz Vector from remote URL
        ansible.builtin.get_url:
            url: https://packages.timber.io/vector/latest/vector-x86_64-unknown-linux-gnu.tar.gz
            dest: /tmp/vector-x86_64-unknown-linux-gnu.tar.gz
            timeout: 60
            force: true
            validate_certs: false
            mode: 0644
      - name: Create directrory for Vector
        ansible.builtin.file:
            state: directory
            path: /var/lib/vector
            mode: 0644
      - name: Extract Vector in the installation directory
        ansible.builtin.unarchive:
            copy: false
            src: /tmp/vector-x86_64-unknown-linux-gnu.tar.gz
            dest: /usr/local/bin
            extra_opts: [--strip-components=2]
